"""empty message

Revision ID: 7bed9c90dff1
Revises: cdb2942c2b59
Create Date: 2021-04-28 16:39:17.106060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bed9c90dff1'
down_revision = 'cdb2942c2b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_userId_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_postId_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'posts', ['postId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_postId_fkey', 'comments', 'posts', ['postId'], ['id'])
    op.create_foreign_key('comments_userId_fkey', 'comments', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
